export const FETCH_BOOK_MAIN_PAGE = 'FETCH_BOOK_MAIN_PAGE';
export const FETCH_BOOK_MAIN_PAGE_START = 'FETCH_BOOK_MAIN_PAGE_START';
export const FETCH_BOOK_MAIN_PAGE_SUCCESS = 'FETCH_BOOK_MAIN_PAGE_SUCCESS';
export const FETCH_BOOK_MAIN_PAGE_FAILURE = 'FETCH_BOOK_MAIN_PAGE_FAILURE';

export const FETCH_BOOK_READING_HISTORY = 'FETCH_BOOK_READING_HISTORY';
export const FETCH_BOOK_READING_HISTORY_SUCCESS = 'FETCH_BOOK_READING_HISTORY_SUCCESS';
export const SAVE_BOOK_READING_HISTORY = 'SAVE_BOOK_READING_HISTORY';

export const FETCH_BOOK_TOC = 'FETCH_BOOK_TOC';
export const FETCH_BOOK_TOC_START = 'FETCH_BOOK_TOC_START';
export const STORE_BOOK_TOC = 'STORE_BOOK_TOC';
