export const FETCH_BOOK_MAIN_PAGE = 'FETCH_BOOK_MAIN_PAGE';
export const FETCH_BOOK_MAIN_PAGE_START = 'FETCH_BOOK_MAIN_PAGE_START';
export const FETCH_BOOK_MAIN_PAGE_SUCCESS = 'FETCH_BOOK_MAIN_PAGE_SUCCESS';
export const FETCH_BOOK_MAIN_PAGE_FAILURE = 'FETCH_BOOK_MAIN_PAGE_FAILURE';
