export default {
    UNORDERED_LIST: 'UNORDERED_LIST',
    ORDERED_LIST: 'ORDERED_LIST',
    LIST_ITEM: 'LIST_ITEM',
    BOLD: 'BOLD',
    EMPH: 'EMPH',
    STRIKE: 'STRIKE',

    CODE: 'CODE',
    CODE_OPERATOR: 'CODE_OPERATOR',
    CODE_STRING: 'CODE_STRING',
    CODE_NUMBER: 'CODE_NUMBER',
    CODE_NAME: 'CODE_NAME',
    CODE_BOOLEAN: 'CODE_BOOLEAN',
    CODE_KEYWORD: 'CODE_KEYWORD',
    CODE_COMMENT: 'CODE_COMMENT',
    CODE_CLASSNAME: 'CODE_CLASSNAME',
    CODE_REGEXP: 'CODE_REGEXP',
    CODE_VARIABLE: 'CODE_VARIABLE',
    CODE_ESCAPED: 'CODE_ESCAPED',

    TITLE: 'TITLE',
    INDEX_TERM: 'INDEX_TERM',
    DEFINITION: 'DEFINITION',
    DEFINITION_TERM: 'DEFINITION_TERM',
    DEFINITION_DESCR: 'DEFINITION_DESCR',

    TIP: 'TIP',
    NOTE: 'NOTE',
    CAUTION: 'CAUTION',
    WARNING: 'WARNING',
    
    FRAMED: 'FRAMED',
    SIMPLE: 'SIMPLE',

    LEVEL_IND: 'LEVEL_IND',
    LEVEL_0: 'LEVEL_0',
    LEVEL_1: 'LEVEL_1',
    LEVEL_2: 'LEVEL_2',
    LEVEL_3: 'LEVEL_3',
    LEVEL_4: 'LEVEL_4',

    FIGURE: 'FIGURE',
    LISTING: 'LISTING',

    TABLE_BODY: 'TABLE_BODY',
    TABLE_ROW: 'TABLE_ROW',
    TABLE_CELL: 'TABLE_CELL',
    TABLE_HEADER: 'TABLE_HEADER',
    TABLE_HEADER_CELL: 'TABLE_HEADER_CELL',
    CAPTION: 'CAPTION',

    ERROR: 'ERROR',

    SUP: 'SUP',

    FOOTNOTE_REF: 'FOOTNOTE_REF',
    FOOTNOTE: 'FOOTNOTE',

    EPIGRAPH: 'EPIGRAPH',

    SIDEBAR: 'SIDEBAR',
};
